const mongoose = require("mongoose");

const reportedIncidentSchema = new mongoose.Schema(
  {
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "user",
    },
    firstName: {
      type: String,
      default: null,
      trim: true,
      min: 3,
      max: 20,
    },
    lastName: {
      type: String,
      default: null,
      trim: true,
      min: 3,
      max: 20,
    },
    email: { type: String, default: null, required: true },
    address: {
      type: String,
      trim: true,
      min: 10,
      max: 100,
      required: true,
    },
    countryName: {
      type: String,
      required: true,
      enum: [
        "Afghanistan",
      "Åland Islands",
      "Albania",
      "Algeria",
      "American Samoa",
      "Andorra",
      "Angola",
      "Anguilla",
      "Antarctica",
      "Antigua and Barbuda",
      "Argentina",
      "Armenia",
      "Aruba",
      "Australia",
      "Austria",
      "Azerbaijan",
      "Bahamas (the)",
      "Bahrain",
      "Bangladesh",
      "Barbados",
      "Belarus",
      "Belgium",
      "Belize",
      "Benin",
      "Bermuda",
      "Bhutan",
      "Bolivia (Plurinational State of)",
      "Bonaire, Sint Eustatius and Saba",
      "Bosnia and Herzegovina",
      "Botswana",
      "Bouvet Island",
      "Brazil",
      "British Indian Ocean Territory (the)",
      "Brunei Darussalam",
      "Bulgaria",
      "Burkina Faso",
      "Burundi",
      "Cabo Verde",
      "Cambodia",
      "Cameroon",
      "Canada",
      "Cayman Islands (the)",
      "Central African Republic (the)",
      "Chad",
      "Chile",
      "China",
      "Christmas Island",
      "Cocos (Keeling) Islands (the)",
      "Colombia",
      "Comoros (the)",
      "Congo (the Democratic Republic of the)",
      "Congo (the)",
      "Cook Islands (the)",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Curaçao",
      "Cyprus",
      "Czechia",
      "Côte d'Ivoire",
      "Denmark",
      "Djibouti",
      "Dominica",
      "Dominican Republic (the)",
      "Ecuador",
      "Egypt",
      "El Salvador",
      "Equatorial Guinea",
      "Eritrea",
      "Estonia",
      "Eswatini",
      "Ethiopia",
      "Falkland Islands (the) [Malvinas]",
      "Faroe Islands (the)",
      "Fiji",
      "Finland",
      "France",
      "French Guiana",
      "French Polynesia",
      "French Southern Territories (the)",
      "Gabon",
      "Gambia (the)",
      "Georgia",
      "Germany",
      "Ghana",
      "Gibraltar",
      "Greece",
      "Greenland",
      "Grenada",
      "Guadeloupe",
      "Guam",
      "Guatemala",
      "Guernsey",
      "Guinea",
      "Guinea-Bissau",
      "Guyana",
      "Haiti",
      "Heard Island and McDonald Islands",
      "Holy See (the)",
      "Honduras",
      "Hong Kong",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran (Islamic Republic of)",
      "Iraq",
      "Ireland",
      "Isle of Man",
      "Israel",
      "Italy",
      "Jamaica",
      "Japan",
      "Jersey",
      "Jordan",
      "Kazakhstan",
      "Kenya",
      "Kiribati",
      "Korea (the Democratic People's Republic of)",
      "Korea (the Republic of)",
      "Kuwait",
      "Kyrgyzstan",
      "Lao People's Democratic Republic (the)",
      "Latvia",
      "Lebanon",
      "Lesotho",
      "Liberia",
      "Libya",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Macao",
      "Madagascar",
      "Malawi",
      "Malaysia",
      "Maldives",
      "Mali",
      "Malta",
      "Marshall Islands (the)",
      "Martinique",
      "Mauritania",
      "Mauritius",
      "Mayotte",
      "Mexico",
      "Micronesia (Federated States of)",
      "Moldova (the Republic of)",
      "Monaco",
      "Mongolia",
      "Montenegro",
      "Montserrat",
      "Morocco",
      "Mozambique",
      "Myanmar",
      "Namibia",
      "Nauru",
      "Nepal",
      "Netherlands (the)",
      "New Caledonia",
      "New Zealand",
      "Nicaragua",
      "Niger (the)",
      "Nigeria",
      "Niue",
      "Norfolk Island",
      "Northern Mariana Islands (the)",
      "Norway",
      "Oman",
      "Pakistan",
      "Palau",
      "Palestine, State of",
      "Panama",
      "Papua New Guinea",
      "Paraguay",
      "Peru",
      "Philippines (the)",
      "Pitcairn",
      "Poland",
      "Portugal",
      "Puerto Rico",
      "Qatar",
      "Republic of North Macedonia",
      "Romania",
      "Russian Federation (the)",
      "Rwanda",
      "Réunion",
      "Saint Barthélemy",
      "Saint Helena, Ascension and Tristan da Cunha",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Martin (French part)",
      "Saint Pierre and Miquelon",
      "Saint Vincent and the Grenadines",
      "Samoa",
      "San Marino",
      "Sao Tome and Principe",
      "Saudi Arabia",
      "Senegal",
      "Serbia",
      "Seychelles",
      "Sierra Leone",
      "Singapore",
      "Sint Maarten (Dutch part)",
      "Slovakia",
      "Slovenia",
      "Solomon Islands",
      "Somalia",
      "South Africa",
      "South Georgia and the South Sandwich Islands",
      "South Sudan",
      "Spain",
      "Sri Lanka",
      "Sudan (the)",
      "Suriname",
      "Svalbard and Jan Mayen",
      "Sweden",
      "Switzerland",
      "Syrian Arab Republic",
      "Taiwan (Province of China)",
      "Tajikistan",
      "Tanzania, United Republic of",
      "Thailand",
      "Timor-Leste",
      "Togo",
      "Tokelau",
      "Tonga",
      "Trinidad and Tobago",
      "Tunisia",
      "Turkey",
      "Turkmenistan",
      "Turks and Caicos Islands (the)",
      "Tuvalu",
      "Uganda",
      "Ukraine",
      "United Arab Emirates (the)",
      "United Kingdom of Great Britain and Northern Ireland (the)",
      "United States Minor Outlying Islands (the)",
      "United States of America (the)",
      "Uruguay",
      "Uzbekistan",
      "Vanuatu",
      "Venezuela (Bolivarian Republic of)",
      "Viet Nam",
      "Virgin Islands (British)",
      "Virgin Islands (U.S.)",
      "Wallis and Futuna",
      "Western Sahara",
      "Yemen",
      "Zambia",
      "Zimbabwe"
      ]
    },
    city:{
      type: String,
      required: true,
    },
    state:{
      type: String,
      required: true,
    },
    longtitude :{
      type: String,
      required: true,
    },
    latitude :{
      type: String,
      required: true,
    },
    countryCode: {
      type: String,
      enum: [
        "",
        "AW +297",
        "AO +244",
        "AF +93",
        "AI +1",
        "AX +358",
        "AL +355",
        "AD +376",
        "AE +971",
        "AR +54",
        "AM +374",
        "AS +1684",
        "AQ +672",
        "TF +262",
        "AG +1",
        "AU +61",
        "AT +43",
        "AZ +994",
        "BI +257",
        "BE +32",
        "BJ +229",
        "BQ +599",
        "BF +226",
        "BD +880",
        "BG +359",
        "BH +973",
        "BS +1",
        "BA +387",
        "BL +590",
        "BY +375",
        "BZ +501",
        "BM +1",
        "BO +591",
        "BR +55",
        "BB +1246",
        "BN +673",
        "BT +975",
        "BV +55",
        "BW +267",
        "CF +236",
        "CA +1",
        "CC +61",
        "CH +41",
        "CL +56",
        "CN +86",
        "CI +225",
        "CM +237",
        "CD +243",
        "CG +242",
        "CK +682",
        "CO +57",
        "KM +269",
        "CV +238",
        "CR +506",
        "CW +599",
        "CX +61",
        "KY +1",
        "CY +357",
        "CZ +420",
        "DE +49",
        "DJ +253",
        "DM +1",
        "DK +45",
        "DO +1",
        "DZ +213",
        "EC +593",
        "EG +20",
        "ER +291",
        "EH +212",
        "ES +34",
        "EE +372",
        "ET +251",
        "FI +358",
        "FJ +679",
        "FK +500",
        "FR +33",
        "FO +298",
        "FM +691",
        "GA +241",
        "GB +44",
        "GE +995",
        "GG +44",
        "GH +233",
        "GI +350",
        "GN +224",
        "GP +590",
        "GM +220",
        "GW +245",
        "GQ +240",
        "GR +30",
        "GD +1",
        "GL +299",
        "GT +502",
        "GF +594",
        "GU +1",
        "GY +592",
        "HK +852",
        "HM +672",
        "HN +504",
        "HR +385",
        "HT +509",
        "HU +36",
        "ID +62",
        "IM +44",
        "IN +91",
        "IO +246",
        "IE +353",
        "IS +354",
        "IL +972",
        "IT +39",
        "JM +1876",
        "JE +44",
        "JO +962",
        "JP +81",
        "KZ +7",
        "KE +254",
        "KG +996",
        "KH +855",
        "KI +686",
        "KN +1",
        "KR +82",
        "XK +383",
        "KW +965",
        "LA +856",
        "LB +961",
        "LR +231",
        "LY +218",
        "LC +1",
        "LI +423",
        "LK +94",
        "LS +266",
        "LT +370",
        "LU +352",
        "LV +371",
        "MO +853",
        "MF +590",
        "MA +212",
        "MC +377",
        "MD +373",
        "MG +261",
        "MV +960",
        "MX +52",
        "MH +692",
        "MK +389",
        "ML +223",
        "MT +356",
        "MM +95",
        "ME +382",
        "MN +976",
        "MP +1670",
        "MZ +258",
        "MR +222",
        "MS +1",
        "MQ +596",
        "MU +230",
        "MW +265",
        "MY +60",
        "YT +262",
        "NA +264",
        "NC +687",
        "NE +227",
        "NF +672",
        "NG +234",
        "NI +505",
        "NU +683",
        "NL +31",
        "NO +47",
        "NP +977",
        "NR +674",
        "NZ +64",
        "OM +968",
        "PK +92",
        "PA +507",
        "PN +64",
        "PE +51",
        "PH +63",
        "PW +680",
        "PG +675",
        "PL +48",
        "PR +1",
        "PT +351",
        "PY +595",
        "PS +970",
        "PF +689",
        "QA +974",
        "RE +262",
        "RO +40",
        "RU +7",
        "RW +250",
        "SA +966",
        "SD +249",
        "SN +221",
        "SG +65",
        "GS +500",
        "SH +290",
        "SJ +47",
        "SB +677",
        "SL +232",
        "SV +503",
        "SM +378",
        "SO +252",
        "PM +508",
        "RS +381",
        "SS +211",
        "ST +239",
        "SR +597",
        "SK +421",
        "SI +386",
        "SE +46",
        "SZ +268",
        "SX +1721",
        "SC +248",
        "TC +1",
        "TD +235",
        "TG +228",
        "TH +66",
        "TJ +992",
        "TK +690",
        "TM +993",
        "TL +670",
        "TO +676",
        "TT +1868",
        "TN +216",
        "TR +90",
        "TV +688",
        "TW +886",
        "TZ +255",
        "UG +256",
        "UA +380",
        "UM +1",
        "UY +598",
        "US +1",
        "UZ +998",
        "VA +39",
        "VC +1",
        "VE +58",
        "VG +1",
        "VI +1",
        "VN +84",
        "VU +678",
        "WF +681",
        "WS +685",
        "YE +967",
        "ZA +27",
        "ZM +260",
        "ZW +263",
      ],
      default: null,
    },
    phoneNo: { type: String, default: null },
    incidentStartDate: { type: Object, default: null, required: true },
    incidentTime: { type: Object, default: null, required: true },
    incidentDuration: { type: Object, default: null, required: true },
    incidentDesc: {
      type: String,
      default: null,
      required: true,
      min: 20,
      max: 1000,
      default: null,
      required: true,
    },
    timeOfDay: {
      type: String,
      enum: ["morning", "day", "evening", "night", "unknown"],
      default: "unknown",
      required: true,
    },
    weather: {
      type: String,
      enum: [
        "indoors",
        "clear",
        "cloudy",
        "rain",
        "thunderstorm",
        "lightningbutnorain",
        "hurricane",
        "tornado",
        "tsunami",
        "other",
      ],
      default: null,
      required: true,
    },
    cloudFormation: {
      type: String,
      enum: [
        "nocloud",
        "cumulus",
        "stratus",
        "stratocumulus",
        "altocumulus",
        "nimbostratus",
        "altostratus",
        "cirrus",
        "cirrocumulus",
        "cirrostratus",
        "unknown",
      ],
      default: null,
      required: true,
    },
    UAPDetected: {
      type: String,
      enum: ["yes", "no", "unknown"],
      default: "unknown",
      required: true,
    },
    noOfUAPs: { type: Number, default: null },
    lifeFormsDetected: {
      type: String,
      enum: ["yes", "no", "unknown"],
      default: "unknown",
      required: true,
    },
    noOfLifeForms: { type: Number, default: null },
    UAPShape: {
      type: String,
      enum: [
        "tictac",
        "light",
        "disk",
        "triangle",
        "cigarshape",
        "circular",
        "largesquare",
        "multishape",
        "antenna",
        "jellyfish",
        "bell",
        "tophat",
        "star",
        "balloon",
        "other",
        "unknown",
      ],
      default: "unknown",
    },
    UAPSize: { type: Number, default: null },
    sizeUnit: {
      type: String,
      enum: ["feet", "meters", "miles", "kilometers", "inches"],
      default: "feet",
    },
    lightEmissions: {
      type: String,
      enum: ["yes", "no", "unknown"],
      default: "unknown",
    },
    colorOfLight: {
      type: String,
      enum: [
        "multicolor",
        "white",
        "orange",
        "purple",
        "red",
        "green",
        "blue",
        "yellow",
        "black",
        "brown",
        "pink",
        "other",
        "unknown",
      ],
    },
    colorOfUAP: {
      type: String,
      enum: [
        "grey/silver/metallic",
        "black",
        "multicolor",
        "white",
        "orange",
        "purple",
        "red",
        "green",
        "blue",
        "yellow",
        "brown",
        "pink",
        "other",
        "unknown",
      ],
    },
    sound: { type: String, default: null },
    animalReactions: { type: String, default: null },
    radarData: {
      type: String,
      enum: ["yes", "no", "unknown"],
      default: "unknown",
    },
    emfEffects: {
      type: String,
      enum: ["yes", "no", "unknown"],
      default: "unknown",
    },
    radiation: {
      type: String,
      enum: ["yes", "no", "unknown"],
      default: "unknown",
    },
    direction: {
      type: String,
      enum: ["etw", "wte", "nts", "stn", "md", "unknown"],
      default: "unknown",
    },
    jetPropulsion: {
      type: String,
      enum: ["yes", "no", "unknown"],
      default: "unknown",
    },
    wingsOrPropellers: {
      type: String,
      enum: ["yes", "no", "unknown"],
      default: "unknown",
    },
    speed: { type: Number, default: null },
    speedUnit: { type: String, enum: ["mph", "km/h"], default: "mph" },
    altitude: { type: Number, default: null },
    altitudeUnit: {
      type: String,
      enum: ["meters", "miles", "kilometers"],
      default: "meters",
    },
    distance: { type: Number, default: null },
    distanceUnit: {
      type: String,
      enum: ["feet", "meters", "miles", "kilometers", "inches"],
      default: "feet",
    },
    cloakingOrInvisibility: {
      type: String,
      enum: ["yes", "no", "unknown"],
      default: "unknown",
    },
    additionalMovement: { type: String, default: null },
    lifeFormSpecies: {
      type: String,
      enum: [
        "human",
        "humanoid",
        "greys",
        "reptilian",
        "cryptozoological",
        "multiplespecies",
        "other",
        "unknown",
      ],
      default: "unknown",
    },
    clothed: {
      type: String,
      enum: ["yes", "no", "unknown"],
      default: "unknown",
    },
    uniformed: {
      type: String,
      enum: ["yes", "no", "unknown"],
      default: "unknown",
    },
    helmet: {
      type: String,
      enum: ["yes", "no", "unknown"],
      default: "unknown",
    },
    avatarOrDrone: {
      type: String,
      enum: ["yes", "no", "unknown"],
      default: "unknown",
    },
    eyeSize: {
      type: String,
      enum: ["large", "small", "none", "other", "unknown"],
      default: "unknown",
    },
    eyeType: {
      type: String,
      enum: ["almond", "circular", "other", "unknown"],
      default: "unknown",
    },
    height: {
      type: String,
      enum: ["tall", "short", "average", "other", "unknown"],
      default: "unknown",
    },
    heightValue: { type: Number, default: null },
    lifeFormMeasurement: {
      type: String,
      enum: ["feet", "meters", "inches"],
      default: "feet",
    },
    physique: {
      type: String,
      enum: ["muscular", "thin", "average", "obese", "other", "unknown"],
      default: "unknown",
    },
    consciousEffects: {
      type: String,
      enum: [
        "conscious",
        "intoxicated",
        "sleepy",
        "concussed",
        "confused",
        "other",
        "unknown",
      ],
      default: "unknown",
      required: true,
    },
    additionalWitnesses: {
      type: String,
      enum: ["yes", "no", "unknown"],
      default: "unknown",
      required: true,
    },
    noOfWitnesses: { type: Number, default: null },
    mentalStateOfObserver: {
      type: String,
      enum: [
        "ofsoundmind",
        "anxiety",
        "depressed",
        "mentaldisorder",
        "other",
        "unknown",
      ],
      default: "unknown",
    },
    trustFactor: {
      type: String,
      enum: ["reliable", "unreliabe", "unknown", "other"],
      default: "unknown",
    },
    additionalWitnessInform: { type: String, default: null },
    additionalComments: { type: String, default: null },
    incidentImage: { type: Array, default: null },
    incidentfiles: { type: Array, default: null },
    incidentLink: { type: String, default: null },
  },
  { timestamps: true }
);

module.exports = mongoose.model("reportedIncident", reportedIncidentSchema);